#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Linux)
      env CFLAGS=-O2 pkg ensure www/squid www/squid3
      ;;
    *)
      pkg ensure www/squid www/squid3
      ;;
  esac

  runmany 'localhost -m file -- state=directory dest="$1"' "/data/squid/cache" "/data/squid/logs" "/data/squid/run"
}

bootstrap
