#!/usr/bin/env bash

function squid_cibuild {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  git clean -fdx
  mkdir -p "$shome/work"

  mkdir -p ~/.ssh
  cat <<EOF | tee -a ~/.ssh/config
Host github.com
  StrictHostKeyChecking no
  ForwardAgent no

EOF

  if [[ ! -d "$shome/work/block/.git" ]]; then
    (cd "$shome/work" && git clone git@github.com:imma/block)
  fi
  "$shome/work/block/script/cibuild"
  source "$shome/work/block/script/profile"

  block gen cibuild

  if [[ ! -d "$shome/work/cache/.git" ]]; then
    (cd "$shome/work" && git clone git@github.com:imma/cache)
  fi
  "$shome/work/block/script/cibuild" "$shome/work/cache"
  pushd "$shome/work/cache" >/dev/null
  require
  popd >/dev/null

  "$shome/work/block/script/cibuild" "$@"
  require
}

squid_cibuild "$@"
