#!/usr/bin/env bash

function squid_cibuild {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  mkdir -p "$shome/work"

  echo '{ "require": [ "block", "cache" ] }' > Blockfile.json.site

  if [[ ! -d "$shome/work/block/.git" ]]; then
    (cd "$shome/work" && git clone git@github.com:imma/block)
  fi
  "$shome/work/block/script/cibuild"
  source "$shome/work/block/script/profile"

  if [[ ! -d "$shome/work/cache/.git" ]]; then
    (cd "$shome/work" && git clone git@github.com:imma/cache)
  fi
  "$shome/work/block/script/cibuild" "$shome/work/cache"
  pushd "$shome/work/cache" >/dev/null
  require
  popd >/dev/null

  "$shome/work/block/script/cibuild" "$@"
  require
}

squid_cibuild "$@"
