#!/usr/bin/env bash

function squid_console {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  ssh -A -p 2222 ubuntu@localhost -- "$@"
}

squid_console "$@"
