#!/usr/bin/env bash

function squid_server {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  case "${1:-}" in
    default)
      "$shome/script/update"
      rm -f /data/squid/run/squid.pid
      exec squid -N -d 1 -f "/data/squid/squid.conf"
      ;;
    *)
      echo "ERROR: unknown server command: ${1:-/not-supplied/}" 1>&2
      return 1
      ;;
  esac
}

squid_server "$@"
