#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cat "$shome/etc/squid.conf.template" > "$shome/etc/squid.conf.tmp"
  mv "$shome/etc/squid.conf.tmp" "$shome/etc/squid.conf"
  mkdir -p "/data/squid/cache"
  squid -f "$shome/etc/squid.conf" -zN
}

bootstrap

