#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  mkdir -p "/data/squid/cache"
  mkdir -p "/data/squid/logs"
  squid -f "/config/squid/squid.conf" -zN
}

bootstrap

